---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?

I think I have a great handle on English vocabulary and making use of uncommon but very succint words when it comes to descriptive writing. I have issues with starting a draft (due to attention deficiency issues), and submitting "poor quality" first drafts for the sake of getting it out of the way. I have a need to make all my writing as polished as possible, even when I know it will still be edited and changed down the line. To further develop my skills, I will get used to the "word dumping" method where I type out all my thoughts onto the page, despite being clunky or unpolished, then proceed with editing later on. This will hopefully get me over the barrier of beginning writing assignments and help get the ball rolling instead of doing everything in one sitting.

# Reflect on writing more generally

- What principles of composition discussed today did you find most useful?

I found "omit words when not useful" to be very useful (haha), since I often fall victim to using flowery language to hide my lack of technical knowledge in a subject. 

- If you were going to formulate your own writing rules, what would they be?

Formulate thoughts in a non-prose manner first (e.g. bullet points, mind maps, scribbling), then write a sentence or two from each point/mark. From these, develop the complete essay.

# Commit your reflections to writing

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.

The hardest part of writing is starting. Therefore, use any and all tools necessary to get over the initial barrier and proceed with polishing and editing the work later. Also, involve people other than yourself to ensure that the information is adequately communicable.
